const { chromium } = require('./lib.js').playwright;
const mkTiff = require('./mktiff.js');
const http = require('http'), fs = require('fs'), path = require('path');
const S = require('./lib.js').OUT;
http.createServer((q, r) => { const p = path.join(require('./lib.js').ROOT, q.url.split('?')[0] === '/' ? 'index.html' : decodeURIComponent(q.url.split('?')[0])); fs.readFile(p, (e, d) => { if (e) { r.statusCode = 404; r.end(); } else { r.setHeader('Content-Type', {js:'text/javascript',css:'text/css',html:'text/html',gpx:'application/gpx+xml'}[p.split('.').pop()]||'image/png'); r.end(d); } }); }).listen(8148, async () => {
  const f = (lon, lat) => 2000 + (lon + 120.66) * 5000 + (lat - 39.59) * 3000;
  const b = await chromium.launch(require('./lib.js').launchOpts);
  const ctx = await b.newContext({ viewport: { width: 1300, height: 1000 } });
  await ctx.route(/tile\.openstreetmap/, r => r.fulfill({ status: 200, contentType: 'image/png', body: fs.readFileSync(S + '/tile.png') }));
  let reqs = 0;
  await ctx.route('**/elevation.nationalmap.gov/**', async (route) => {
    reqs++; const u = new URL(route.request().url()); const [west, south, east, north] = u.searchParams.get('bbox').split(',').map(Number); const [w, h] = u.searchParams.get('size').split(',').map(Number);
    const arr = new Float32Array(w * h); for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) arr[j * w + i] = f(west + (i + .5) / w * (east - west), north - (j + .5) / h * (north - south));
    await route.fulfill({ status: 200, contentType: 'image/tiff', headers: { 'access-control-allow-origin': '*' }, body: mkTiff(arr, w, h) });
  });
  const pg = await ctx.newPage(); await pg.addInitScript(() => { window.__MAPNC_FREE_PANES = true; }); const errs = []; pg.on('pageerror', e => errs.push(e.message));
  const check = (n, ok, x) => console.log((ok ? 'PASS ' : 'FAIL ') + n + (x ? '  ' + x : ''));
  const ready = () => pg.waitForSelector('#result-info:not([hidden])', { timeout: 15000 });

  const txt = (id) => pg.locator('#' + id).innerText();
  await pg.goto('http://localhost:8148/');
  check('Heightmap view disabled before elevation', await pg.locator('#view-hm').isDisabled() && await pg.locator('#view-map').getAttribute('aria-pressed') === 'true');
  await ready();
  check('Heightmap view enabled with elevation', !(await pg.locator('#view-hm').isDisabled()));
  check('map is the default view', await pg.locator('#map').isVisible() && !(await pg.locator('#hm-view').isVisible()));
  await pg.click('#view-hm');
  check('switches to the heightmap, map hidden', await pg.locator('#hm-view').isVisible() && !(await pg.locator('#map').isVisible()) && (await pg.getAttribute('#view-hm', 'aria-pressed')) === 'true');
  const box = await pg.locator('#hm-canvas').boundingBox(), st = await pg.locator('#stage').boundingBox();
  check('canvas fills the stage', box.width > st.width * 0.6 && box.height > st.height * 0.6, JSON.stringify([box.width | 0, box.height | 0, st.width | 0, st.height | 0]));
  const dim = await pg.evaluate(() => [document.getElementById('hm-canvas').width, document.getElementById('hm-canvas').height, window.MapNC.elevation.width, window.MapNC.elevation.height]);
  check('canvas holds the full-resolution grid', dim[0] === dim[2] && dim[1] === dim[3], dim.join('x'));
  const redPx = () => pg.evaluate(() => { const c = document.getElementById('hm-canvas'), d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data; let n = 0; for (let i = 0; i < d.length; i += 4) if (d[i] > 180 && d[i + 1] < 90 && d[i + 2] < 120) n++; return n; });
  check('route is drawn on the heightmap', (await redPx()) > 200, String(await redPx()));
  await pg.uncheck('#route-guide'); await pg.waitForTimeout(500);
  check('route can be hidden', (await redPx()) === 0);
  await pg.check('#route-guide'); await pg.waitForTimeout(500);
  const cx = box.x + box.width / 2, cy = box.y + box.height / 2;
  await pg.mouse.move(cx, cy);
  check('hover shows elevation and position', /\d+\.\d m · \d+\.\d+[NS] \d+\.\d+[EW]/.test(await txt('hm-readout')), await txt('hm-readout'));
  const el0 = await txt('hm-readout'); await pg.mouse.move(cx + box.width * 0.3, cy);
  check('readout follows the pointer', (await txt('hm-readout')) !== el0, await txt('hm-readout'));
  await pg.mouse.move(st.x + 2, st.y + st.height - 2); await pg.waitForTimeout(100);
  check('readout hides outside the image', !(await pg.locator('#hm-readout').isVisible()));
  await pg.click('#view-map');
  check('back to the map', await pg.locator('#map').isVisible() && !(await pg.locator('#hm-view').isVisible()));
  const sz = await pg.evaluate(() => { const m = document.getElementById('map').getBoundingClientRect(), s = document.getElementById('stage').getBoundingClientRect(); return [m.width, m.height, s.width, s.height]; });
  check('map refills the stage', Math.abs(sz[0] - sz[2]) < 2 && Math.abs(sz[1] - sz[3]) < 2, sz.join(','));
  await pg.click('#show-hm'); check('sidebar button opens the heightmap', await pg.locator('#hm-view').isVisible());
  await pg.click('#view-map');
  await pg.click('summary:has-text("Clean up")');
  await pg.click('#edit-toggle');
  check('editing returns to the map and disables the heightmap', await pg.locator('#map').isVisible() && await pg.locator('#view-hm').isDisabled());
  await pg.keyboard.press('Escape');
  check('heightmap available again after editing', !(await pg.locator('#view-hm').isDisabled()));
  console.log('page errors:', errs); await b.close(); process.exit(0);
});
